#!/bin/sh
# git-hooks: this file is created by git-hooks
# https://github.com/amazingandyyy/git-hooks

CURRENT_NAME=`basename $0`

if [ -f "node_modules/@amazingandyyy/git-hooks/run.js" ]; then
  node node_modules/@amazingandyyy/git-hooks/run.js $CURRENT_NAME
else
  node run.js $CURRENT_NAME
fi;

# This is the end of the file